import chepy.core
from typing import Any

class Chepy_Forensics(chepy.core.ChepyCore):
    state: Any = ...
    def file_mime(self): ...
    def file_magic(self): ...
    def get_metadata(self): ...
    def embedded_files(self, extract_path: str=...) -> Any: ...
