import chepy.core
from typing import Any, TypeVar

Chepy_MLT = TypeVar('Chepy_MLT', bound='Chepy_ML')

class Chepy_ML(chepy.core.ChepyCore):
    state: Any = ...
    def ml_magic(self: Chepy_MLT, depth:int=3, verbose: bool=False) -> Chepy_MLT: ...
    def ml_detect(self: Chepy_MLT, num_top_labels:int=...) -> Chepy_MLT: ...
