import chepy.core
from typing import Any

class Chepy_Extract(chepy.core.ChepyCore):
    state: Any = ...
    def extract_common_secrets(self, case_insensitive: bool = ...) -> Any: ...
    def jpath_selector(self, query: str): ...
    def php_deserialize(self): ...
    def minify_xml(self): ...
    def beautify_xml(self): ...
